#########################################################################################
#                                                                                       #
# This program and the accompanying materials are made available under the terms of the #
# Eclipse Public License v2.0 which accompanies this distribution, and is available at  #
# https://www.eclipse.org/legal/epl-v20.html                                            #
#                                                                                       #
# SPDX-License-Identifier: EPL-2.0                                                      #
#                                                                                       #
# Copyright IBM Corporation 2020                                                        #
#                                                                                       #
#########################################################################################
apiVersion: v1
kind: ConfigMap
metadata:
    name: gateway-config-map
    namespace: {{ .Release.Namespace }}
    labels:
        {{- include "zowe-api-ml.labels" . | nindent 8 }}
data:
    gateway-service.yml: |
        spring.profiles.include: diag
        apiml:
            service:
                hostname: gateway-service
                ipAddress: 0.0.0.0
                port: {{ .Values.gatewayService.service.port }}
                discoveryServiceUrls: https://discovery-service:{{ .Values.discoveryService.service.port }}/eureka/
            security:
                auth:
                    provider: zosmf
                    zosmfServiceId: zosmf
                    passTicket:
                        timeout: 360
                ssl:
                    verifySslCertificatesOfServices: true
                zosmf:
                    useJwtToken: true
                x509:
                    enabled: true
            banner: console
        spring:
            output:
                ansi:
                    enabled: always
            cache:
                ehcache:
                    config: classpath:ehcache.xml
        server:
            internal:
                enabled: true
                port: 10017
                ssl:
                    keyAlias: ${KEY_ALIAS}
                    keyPassword: ${KEY_PASSWORD}
                    {{- if .Values.security.useCertManager }} # Keystore configuration
                    {{- if eq .Values.gatewayService.ssl.keystore.type "PKCS12" }}
                    keyStore: /app/tls/keystore/keystore.p12
                    {{- else }}
                    keyStore: /app/tls/keystore/keystore.jks
                    {{- end }}
                    {{- else }}
                    keyStore: /app/tls/keystore/{{ .Values.gatewayService.ssl.keystore.filename }}
                    {{- end }}
                    keyStorePassword: ${KEYSTORE_PASSWORD}
                    keyStoreType: {{ .Values.gatewayService.ssl.keystore.type }}
                    {{- if .Values.security.useCertManager }} # Truststore configuration
                    {{- if eq .Values.gatewayService.ssl.truststore.type "PKCS12" }}
                    trustStore: /app/tls/truststore/truststore.p12
                    {{- else }}
                    trustStore: /app/tls/truststore/truststore.jks
                    {{- end }}
                    {{- else }}
                    trustStore: /app/tls/truststore/{{ .Values.gatewayService.ssl.truststore.filename }}
                    {{- end }}
                    trustStorePassword: ${TRUSTSTORE_PASSWORD}
                    trustStoreType: {{ .Values.gatewayService.ssl.truststore.type }}
                    clientAuth: want
            ssl:
                keyAlias: ${KEY_ALIAS}
                keyPassword: ${KEY_PASSWORD}
                {{- if .Values.security.useCertManager }} # Keystore configuration
                {{- if eq .Values.gatewayService.ssl.keystore.type "PKCS12" }}
                keyStore: /app/tls/keystore/keystore.p12
                {{- else }}
                keyStore: /app/tls/keystore/keystore.jks
                {{- end }}
                {{- else }}
                keyStore: /app/tls/keystore/{{ .Values.gatewayService.ssl.keystore.filename }}
                {{- end }}
                keyStorePassword: ${KEYSTORE_PASSWORD}
                keyStoreType: {{ .Values.gatewayService.ssl.keystore.type }}
                {{- if .Values.security.useCertManager }} # Truststore configuration
                {{- if eq .Values.gatewayService.ssl.truststore.type "PKCS12" }}
                trustStore: /app/tls/truststore/truststore.p12
                {{- else }}
                trustStore: /app/tls/truststore/truststore.jks
                {{- end }}
                {{- else }}
                trustStore: /app/tls/truststore/{{ .Values.gatewayService.ssl.truststore.filename }}
                {{- end }}
                trustStorePassword: ${TRUSTSTORE_PASSWORD}
                trustStoreType: {{ .Values.gatewayService.ssl.truststore.type }}
