apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\sdk\kube\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: discovery-service
  name: discovery-service
spec:
  ports:
  - name: "10011"
    port: 10011
    targetPort: 10011
  selector:
    io.kompose.service: discovery-service
status:
  loadBalancer: {}
