apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\sdk\kube\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: explorer-mvs
  name: explorer-mvs
spec:
  ports:
  - name: "18548"
    port: 18548
    targetPort: 18548
  selector:
    io.kompose.service: explorer-mvs
status:
  loadBalancer: {}
