apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\sdk\kube\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: gateway-service
  name: gateway-service
spec:
  ports:
  - name: "10010"
    port: 10010
    targetPort: 10010
  selector:
    io.kompose.service: gateway-service
status:
  loadBalancer: {}
