apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: zss-auth-plugin
  name: zss-auth-plugin
spec:
  containers:
  - image: zss-auth-plugin
    imagePullPolicy: "IfNotPresent"
    name: zss-auth-plugin
    resources: {}
    volumeMounts:
    - mountPath: /dropins
      name: dropins-volume
  hostname: zss-auth-plugin
  restartPolicy: Never
  volumes:
  - name: dropins-volume
    persistentVolumeClaim:
      claimName: dropins-volume
status: {}
