services:
- serviceId: explorer-jes
  title: JES Explorer
  description: IBM z/OS Jobs UI service
  catalogUiTileId:
  instanceBaseUrls:
  - https://explorer-jes:18546/
  homePageRelativeUrl:
  routedServices:
  - gatewayUrl: ui/v1
    serviceRelativeUrl: /ui/v1/explorer-jes